### PR TITLE
Fix setuptools

### PR DESCRIPTION
**Pull request by jbusecke**
Fix for #49

### CODE REVIEW

**Comment by jbusecke** [comment]
Huh, that was apparently not the issue...

**Comment by jbusecke** [comment]
It might still be the solution for python 3.12 (I just checked in the other PR, and there this was only a problem with 3.12).

**Comment by jbusecke** [comment]
Also just ran dependabot to see if this might be fixed with an update to the gh actions

**Comment by norlandrhagen** [comment]
https://github.com/leap-stc/leap-data-management-utils/pull/51

**Pull request closed without merging**
